services:
  anime-crop-gpu:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - GRADIO_SERVER_NAME=0.0.0.0
    ports:
      - "7860:7860"
    volumes:
      - ./shared_data:/shared_data
    tty: true
    ipc: host  # --ipc=hostに相当
    ulimits:   # --ulimitオプションに相当
      memlock:
        soft: -1
        hard: -1
      stack:
        soft: 67108864
        hard: 67108864
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
