services:
  anime-crop:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - GRADIO_SERVER_NAME=0.0.0.0
    ports:
      - "7860:7860"
    volumes:
      - ./shared_data:/shared_data
    stdin_open: true  # docker run -i に相当
    tty: true  # docker run -t に相当
